spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never # init at begin then set to never
      schema: classpath:quartz_init.sql
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/myjob
    username: root
    password: Huyhn25062000@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-quartz-demo
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host: smtp.gmail.com
    port: 587
    username: withuwe021@gmail.com
    password: dimflojlousrplwk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

