spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never # init at begin then set to never
      schema: classpath:quartz_init.sql
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate

  datasource:
    url: jdbc:mysql://localhost:3306/myjob
    username: root
    password: Huyhn25062000@
  mail:
    host: smtp.gmail.com
    port: 587
    username: withuwe021@gmail.com
    password: dimflojlousrplwk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

